# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{acts_as_versionable}
  s.version = "2.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Pavel Y.", "Henning Perl"]
  s.date = %q{2010-05-30}
  s.email = %q{henning.perl@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "MIT-LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "acts_as_versionable.gemspec",
     "init.rb",
     "install.rb",
     "lib/acts_as_versionable.rb",
     "lib/generators/USAGE",
     "lib/generators/templates/migration.rb.erb",
     "lib/generators/versionize_generator.rb",
     "uninstall.rb"
  ]
  s.homepage = %q{http://github.com/hperl/acts_as_versionable}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Add support for versions to your model}
  s.test_files = [
    "test/acts_as_versionable_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

